{{- range $key, $value := .Values.persistence }}
{{- if and $value.enabled (eq $value.type "pvc") (empty $value.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" (include "jellystat.fullname" $) $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "jellystat.labels" $ | nindent 4 }}
    {{- range $labelKey, $labelValue := $.Values.extraLabels }}
    {{ $labelKey }}: {{ $labelValue | quote }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml $value.accessModes | nindent 4 }}
  {{- if $value.storageClass }}
  storageClassName: {{ $value.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $value.size | quote }}
---
{{- end }}
{{- end }}
