{{- if or .Values.secretConfig.jwtSecret .Values.secretConfig.postgresPassword .Values.secretConfig.masterUser .Values.secretConfig.masterPassword .Values.secretConfig.geoliteAccountId .Values.secretConfig.geoliteLicenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jellystat.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellystat.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.secretConfig.jwtSecret }}
  jwt-secret: {{ .Values.secretConfig.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretConfig.postgresPassword }}
  postgres-password: {{ .Values.secretConfig.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretConfig.masterUser }}
  master-user: {{ .Values.secretConfig.masterUser | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretConfig.masterPassword }}
  master-password: {{ .Values.secretConfig.masterPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretConfig.geoliteAccountId }}
  geolite-account-id: {{ .Values.secretConfig.geoliteAccountId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretConfig.geoliteLicenseKey }}
  geolite-license-key: {{ .Values.secretConfig.geoliteLicenseKey | b64enc | quote }}
  {{- end }}
{{- end }}
