apiVersion: v2
name: jellystat
description: A Helm chart to deploy Jellystat
type: application
version: 1.0.1
appVersion: "1.0.0"

keywords:
- jellystat
- jellyfin
- statistics
- monitoring

home: https://github.com/CyferShepard/Jellystat
sources:
- https://github.com/CyferShepard/Jellystat
- https://hub.docker.com/r/cyfershepard/jellystat
