apiVersion: v2
name: radarr
description: A Helm chart to deploy Radarr
type: application
version: 1.0.18
appVersion: "4.0.0"

keywords:
- radarr
- movies
- download
- usenet
- bittorrent

home: https://radarr.video/
sources:
- https://github.com/Radarr/Radarr
- https://github.com/linuxserver/docker-radarr # Source for the specific image used
- https://lscr.io/linuxserver/radarr # Image source
